### ISSUE TITLE
Set a custom HTTP User Agent header for tracking

### ISSUE THREAD

**Issue by chrismetcalf** [Chicago/RSocrata#119]
Following up on my conversation with @tomschenkjr yesterday, we should set a custom User Agent header for RSocrata so that I can help get you guys usage analytics.

The [custom header I set for `soda-ruby`](https://github.com/socrata/soda-ruby/blob/master/lib/soda/client.rb#L25) might be a good model:

    soda-ruby/0.2.22 (Linux/2.6.32-573.12.1.el6.x86_64; Ruby/2.3.0-p0)

Gets me not just the gem version, but also the versions of the underlying OS and Ruby interpreter.

**Comment by tomschenkjr** [comment]
This is a great suggestion. Looks like `httr`'s `add_headers()` function will make this an easy feature.

**Comment by tomschenkjr** [comment]
Three functions make HTTP calls to Socrata: `read.socrata()`, `ls.socrata()` and `write.socrata()`. Each function should have headers added to them.

I will create a central function, `fetch_headers()` to compile headers in the following format:

```
RSocrata/{RSocrata version} ({Operating System}/{OS version}; R/{R version})
```

I will insert calls to `fetch_headers` within each one of those functions to ensure a consistent reporting to Socrata.

**Comment by tomschenkjr** [comment]
It seems like I'm almost done with the function. However, after looking at the builds is returning the version after each time `read.socrata()` is ran. [Here](https://travis-ci.org/Chicago/RSocrata/jobs/207944131#L1108) is an example. I'll squash that bit.

I also do not have a unit test for this. I'm not quite sure what the appropriate test would be, though.

**Comment by chrismetcalf** [comment]
@tomschenkjr Hmm. The way to unit test this would be to stub out the HTTP requests with something that'd check to make sure you were setting the right headers. With Ruby that'd be done with something like [vcr](https://github.com/vcr/vcr)

**Comment by tomschenkjr** [comment]
@PriyaDoIT - I neglected to mention that I'm prepping this for 1.7.2 so added it to a milestone. I'm not fixing a bug, but it's minor and doesn't impact the user in any way so makes sense to ship it -- even for a patch release.

**Comment by tomschenkjr** [comment]
@chrismetcalf - thanks for the advice on the unit test.

We've ran a handful of tests with the new headers. Could I bug you to check your logs to make sure you are seeing them?

**Comment by chrismetcalf** [comment]
@tomschenkjr Hmm. I don't see them in the last 7 days of logs. What app token did you use? I can check by that too.

**Comment by tomschenkjr** [comment]
@chrismetcalf - "[ew2rEMuESuzWPqMkyPfOSGJgE](https://github.com/Chicago/RSocrata/blob/issue119/tests/testthat/test-all.R#L332)"

**Comment by tomschenkjr** [comment]
@chrismetcalf - I think I sorted it out since I could test it against http://httpbin.org. Starting with version 1.7.4, RSocrata will have a header which reports its version and platform.
