### ISSUE TITLE
Update CONTRIBUTING.md with policy on supported versions of R

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/RSocrata#132]
Per a core developer team meeting, the RSocrata package will be built to the specs of the current version of R. That is, we may introduce new functions that are incompatible with prior versions of R.

This needs to be documented in the [CONTRIBUTING.md](https://github.com/Chicago/RSocrata/blob/master/CONTRIBUTING.md) file to clarity to us and other contributors.

~~For the time-being, will maintain the `oldrel` [builds in Travis-CI](https://github.com/Chicago/RSocrata/blob/master/.travis.yml), which uses the previous release as the base-R version. This will help us identify when we will have failure with most-recent versions of R will occur.~~

**Comment by tomschenkjr** [comment]
@geneorama and @nicklucius - I've revised my original comment and struckout the test pertaining to maintaining `oldrel` in Travis CI.

If our policy is that build tests must pass, then it makes sense to remove the `oldrel` from Travis-CI builds so we don't have to deal with false-failures (beyond [what we already deal with](https://github.com/Chicago/RSocrata/wiki/Git-Flow#failing-travis-ci-and-appveyor-builds)).

What do you think about removing `oldrel` and forgoing unit testing on penultimate builds?

**Comment by nicklucius** [comment]
@tomschenkjr - By eliminating ```oldrel``` it will be nice to not have to deal with an additional false-failure notification. And since we will be officially building RSocrata to the current R version, I can't think of a reason it would be constructive for us to get information about true-failures on old releases of R.

**Comment by PriyaDoIT** [comment]
@tomschenkjr @nicklucius  can i close this?

**Comment by tomschenkjr** [comment]
Yes. Everything can close except for the one issue with the HTTP headers. The rest of the milestones were finished.
