### ISSUE TITLE
Icons broken on README

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/RSocrata#134]
Just noticed this today, but I'm pretty sure this was just working. The Travis CI, AppVeyor and other little icons are broken. 

The primary suspect is GitHub's [recent change in their Markdown rendering engine](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown).

**Comment by geneorama** [comment]
Thanks for the heads up, this is an exciting development on markdown! (although it may cause some short term pain...)

**Comment by tomschenkjr** [comment]
Ok, figured this out. The new GitHub parser for Markdown does not like spaces in the URL

Below is an incorrect and correct example for a link to a Shields.io badge. In particular, the `label=Linux build` was causing it to not render appropriately.

**Incorrect**
```md
![](https://img.shields.io/travis/Chicago/RSocrata/master.svg?style=flat-square&label=Linux build)
```
**Correct**
```md
![](https://img.shields.io/travis/Chicago/RSocrata/master.svg?style=flat-square&label=Linux%20build)
```
