### ISSUE TITLE
Fix package reference in `export.socrata`

### ISSUE THREAD

**Issue by geneorama** [Chicago/RSocrata#140]
Adding issue per discussion in analytics meeting today

`export.socrata` has a call to `file_ext`, but it should be `tools::file_ext` because tools is not in the default search path. https://github.com/Chicago/RSocrata/blob/dev/R/RSocrata.R#L508

I think it's sufficient to simply add `tools::` because tools is a default package.  I don't think it needs to be added in the `IMPORTS` or `DEPENDS` fields in `DESCRIPTION`.

**Comment by geneorama** [comment]
@tomschenkjr I can't add this to 1.7.4 because the code is only in branch `issue126`

**Comment by tomschenkjr** [comment]
Got it, so only related to #126? 

I've reassigned this issue to the v1.8.0 milestone. Since you're looking at it, can you make the change in `issue126`? Feel free to directly push to it.

**Comment by geneorama** [comment]
I'm not sure why that commit message didn't close this issue, but I'm closing it now.

**Comment by tomschenkjr** [comment]
Got it. For commit-based closures, it only takes effect when it’s on the master branch. So, eventually it would have closed.
