### ISSUE TITLE
Rewrite write.socrata unit test to prevent false failures

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/RSocrata#143]
We test `write.socrata()` function by uploading random data to Socrata and then using `read.socrata()` to download that data and compare the numbers to ensure the write was successful.

Meanwhile, we have adopted a build matrix that tests both the current version of R and also the development version to ensure future compatibility. But we are running into minor issues that the two tests "compete" with each other:
  1. Production build will upload random numbers
  2. Development build will upload random number to the same Socrata dataset
  3. Production build will download random numbers (which were provided by the development instance
  4. Development instance will download the random numbers

Step 3 causes the test to fail. This causes build failures [nearly every day](https://travis-ci.org/Chicago/RSocrata/builds).

However, we could adopt a testing framework which simply checks that `200 OK` is received by the `write.socrata()` command and remove the check on download. That is, we simply check to make sure that Socrata accepted our download.

**Comment by geneorama** [comment]
I noticed something perhaps new in the `testthat` [documentation](http://r-pkgs.had.co.nz/tests.html) which might help.  

Under CRAN Notes:
> Tests need to run relatively quickly - aim for under a minute. Place `skip_on_cran()` at the beginning of long-running tests that shouldn’t be run on CRAN - they’ll still be run locally, but not on CRAN.

They also have `skip_on_travis` and `skip_on_appveyor`, so maybe it would be enough to keep the tests, but skip them on these other systems.  The tests will still run when we build the package locally for upload to CRAN.

**Comment by tomschenkjr** [comment]
That’s a useful function that I’m not sure if I knew of.

However, I don’t think it’s a good solution for this. The repeated CRAN tests helps identify if anything changed with our dependencies (e.g., httr) or an API-related change that breaks our code. It’s possible that some day, `write.socrata()` is broken by something so we’d want to identify that.
