### ISSUE TITLE
Bad Request with SoQL queries

### ISSUE THREAD

**Issue by delsea** [Chicago/RSocrata#146]
Rather new to this, so thanks for the detailed documentation.

I'm attempting to grab only the most recent data from a medicaid database, by using where and max, but keep running into this error "Error in getResponse(validUrl, email, password) : Bad Request (HTTP 400)"  My problem seems similar to #120, but the url called does include &$order=:id

The url that gives this error: "https://data.medicaid.gov/resource/tau9-gfwr.json?$where=as_of_date=max(as_of_date)"

Simple filtering and including the date explicitly gives me what I want but I would prefer to have more flexibility: "https://data.medicaid.gov/resource/tau9-gfwr.json?as_of_date=2017-11-01"

I am using an app token and have a valid email and password.  Thanks!

**Comment by tomschenkjr** [comment]
@delsea - I attempted to replicate the error, but it does not appear that the original query is valid. Copying/pasting it into the browser yields this error: 

```json
{"message":"Query coordinator error: query.soql.aggregate-in-ungrouped-context; Aggregate function 'max' used in ungrouped context: WHERE; position: Map(row -> 1, column -> 299, line -> \"SELECT `ndc_description`, `ndc`, `nadac_per_unit`, `effective_date`, `pricing_unit`, `pharmacy_type_indicator`, `otc`, `explanation_code`, `classification_for_rate_setting`, `corresponding_generic_drug_nadac_per_unit`, `corresponding_generic_drug_effective_date`, `as_of_date` WHERE `as_of_date` = max(`as_of_date`)\\n                                                                                                                                                                                                                                                                                                          ^\")","errorCode":"query.soql.aggregate-in-ungrouped-context","data":{"function":"max","clause":"WHERE","dataset":"alpha.43896","position":{"row":1,"column":299,"line":"SELECT `ndc_description`, `ndc`, `nadac_per_unit`, `effective_date`, `pricing_unit`, `pharmacy_type_indicator`, `otc`, `explanation_code`, `classification_for_rate_setting`, `corresponding_generic_drug_nadac_per_unit`, `corresponding_generic_drug_effective_date`, `as_of_date` WHERE `as_of_date` = max(`as_of_date`)\n                                                                                                                                                                                                                                                                                                          ^"}}}
```
Thus, I think the underlying error is with the original SoDA query. I haven't had a chance to look at the original query itself, but unsure if you can use the `max(...)` argument in the specified way.

I'd recommend posting the query to Socrata direct (support@socrata.com) or asking on StackOverflow.

Let us know if there are other questions or clarification. Since I couldn't replicate, going to close this for now.

**Comment by delsea** [comment]
Thanks for the quick feedback.  I will contact socrata.
