### ISSUE TITLE
Add explicit sorting to query to assure results

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/RSocrata#15]
Per Socrata [SoDA documentation](http://dev.socrata.com/docs/paging.html), the query should be ordered to deliver consistent results if the dataset is changed while the dataset is downloading.

**Comment by geneorama** [comment]
Another useful reference:
http://dev.socrata.com/docs/queries.html#the-limit-parameter

**Comment by marks** [comment]
@tomschenkjr Any thoughts on implementing this? I have run into an issue that appears to be sorting-related. One can add a sort to the URL but it'd be useful, IMHO, to have a default sort applied if one is not specified.

**Comment by tomschenkjr** [comment]
Yeah, we can target this and make it the top priority. It was always a theoretical issue but now it’s impacting, can push a fix.

/cc @geneorama

**Comment by geneorama** [comment]
@marks I'm wondering what issue you found. 

The only reason I suggested the "order" parameter was to ensure reliability for paged queries (queries that require more than one call). Even for paged queries I thought that the only reason the order was important was if rows were inserted in between calls or if Socrata changed the sort of a data set on the back end, both of which I considered to be unlikely and unreproducible events.

**Comment by marks** [comment]
@geneorama the issue I found is with a private dataset and I'm having trouble reproducing it anywhere else.. so I dont have much to share but Socrata engineers are telling me a default sort would be a good practice. As you all probably now, there is a "system field" called `:id` as well as `:created_at` and `:updated_at` which may be suitable for default sorts

**Comment by geneorama** [comment]
Using `:id` seems like a good idea, and I had forgotten about it. I remember discussing it with @tomschenkjr, and I think I had been using it in my own work.  For some reason I didn't end up using it, but I don't remember why.

One issue is that it was only available for .json downloads, maybe that was it?
Maybe it wasn't available for all data sets?

Maybe @tomschenkjr will remember more detail.
