### ISSUE TITLE
Update CRAN for R-3.5

### ISSUE THREAD

**Issue by geneorama** [Chicago/RSocrata#156]

**Comment by tomschenkjr** [comment]
❓
(I'm going to remain pretty active in the development of this one)

**Comment by geneorama** [comment]
Hmmm... strange.  Just got a new laptop image and was installing my R packages. I got an error when I tried to install `RSocrata` saying approximately that "RSocrata is not available for R-3.5".  

I assumed that we needed to rebuild with 3.5 and post to CRAN, however it just now installed without issue. 

Not sure why I got the error, must be a fluke or a temporary issue with the mirror.
