### ISSUE TITLE
Remove dead link and fix Contributing.md link 

### ISSUE THREAD

**Issue by nicklucius** [Chicago/RSocrata#178]
Waffle.io [shut down](https://help.waffle.io/articles/2801857-waffle-shutdown-tl-dr) on 5/16/19, which of course broke our link in README.md. CRAN requires this to be removed.

Separately, the link to CONTRIBUTING.md in README.md is a relative link that uses GitHub markdown shorthand. CRAN requires this to be specified by full URL.

**Comment by geneorama** [comment]
If I'm reading this right there a new error related to issue #19 from Appveyor. We recently had other issues with this example when the publishers changed the data set and appeared to clean up old records.

**Comment by geneorama** [comment]
```
  OK: 139 SKIPPED: 4 WARNINGS: 4 FAILED: 1
684  1. Error: read Socrata JSON with missing fields (issue 19 - binding pages together) (@test-all.R#260) 
685  
686  Error: testthat unit tests failed
687  Execution halted
```

**Comment by geneorama** [comment]
Not sure what that was on Appveyor, I'm not seeing the same thing when I run the tests locally.
