### ISSUE TITLE
Trouble installing package

### ISSUE THREAD

**Issue by daniel-kramer** [Chicago/RSocrata#193]
Hi! I was going to install the package and I got this error message: 

> installed.packages("RSocrata")
     Package LibPath Version Priority Depends Imports LinkingTo Suggests Enhances License
     License_is_FOSS License_restricts_use OS_type Archs MD5sum NeedsCompilation Built

Any tips on how I might go about fixing this? Thanks so much!

**Comment by willsanford** [comment]
Glad this resolved itself quickly!
