### ISSUE TITLE
RSocrate 403 error

### ISSUE THREAD

**Issue by robertaross0** [Chicago/RSocrata#195]
I attempted to execute the following:

`library("RSocrata")

assessments <- read.socrata(
  "https://datacatalog.cookcountyil.gov/resource/tnes-dgyi.json",
  app_token = "aIeNbk5VjuMcQyNcop14zg2Vv",
  email     = "raross1217@gmail.com.com",
  password  = "MY PASSWORD"
)`

and received a 403 error:

2021-08-05 08:23:38.089 getResponse: Error in httr GET: 403  https://datacatalog.cookcountyil.gov/resource/tnes-dgyi.json?%24%24app_token=aIeNbk5VjuMcQyNcop14zg2Vv&$order=:id
Error in getResponse(validUrl, email, password) : Forbidden (HTTP 403).

**Comment by tomschenkjr** [comment]
Talked with Rob and was a syntax issue. No bug.

**Comment by nicklucius** [comment]
Thanks @tomschenkjr! Let us know if you have any other issues, @robertaross0. Closing this one.

**Comment by robertaross0** [comment]
Thanks guys. Rushing + impatience = user error.
