### ISSUE TITLE
Failing CRAN checks, due by 9/10

### ISSUE THREAD

**Issue by nicklucius** [Chicago/RSocrata#196]
See https://cran.r-project.org/web/checks/check_results_RSocrata.html

**Comment by nicklucius** [comment]
CRAN checks are failing because a dataset that we are using for testing no longer exists. The dataset was an example of one that triggered a failure documented in #118. We no longer have an examples of a dataset that would trigger this error. This calls for removing the test since we can't run it on an actual real-life example dataset. 

@geneorama could you take a look at this and if you agree, make the change so we can stay on CRAN? We have 2 days.

**Comment by geneorama** [comment]
I agree, that is the issue. I don't know how to fix the test because I don't know how to find another dataset with missing SODA2 headers. I modified the test to take out the checks and committed it to a new branch, issue196.

**Comment by geneorama** [comment]
@nicklucius I have not updated the DESCRIPTION and put in a pull request.  According to the documentation we should submit the pull request to dev, but that's behind master. Do you want me to make a pull request to master and make it version 1.7.10-7 (currently master is 1.7.10-6)?
