### ISSUE TITLE
Replace http links with https links

### ISSUE THREAD

**Issue by geneorama** [Chicago/RSocrata#201]
CRAN is requesting that we fix the links that are permanently moved, mostly to HTTPS

The relevant portion of the check results: 
```
Found the following (possibly) invalid URLs:
  URL: http://dev.socrata.com (moved to https://dev.socrata.com/)
    From: DESCRIPTION
          README.md
    Status: 200
    Message: OK
  URL: http://dev.socrata.com/consumers/getting-started.html (moved to https://dev.socrata.com/consumers/getting-started.html)
    From: man/read.socrata.Rd
          man/validateUrl.Rd
          man/write.socrata.Rd
    Status: 200
    Message: OK
  URL: http://dev.socrata.com/docs/app-tokens.html (moved to https://dev.socrata.com/docs/app-tokens.html)
    From: README.md
    Status: 200
    Message: OK
  URL: http://dev.socrata.com/docs/queries.html (moved to https://dev.socrata.com/docs/queries.html)
    From: README.md
    Status: 200
    Message: OK
  URL: https://coveralls.io/r/Chicago/RSocrata?branch=dev (moved to https://coveralls.io/github/Chicago/RSocrata)
    From: README.md
    Status: 200
    Message: OK
  URL: https://coveralls.io/r/Chicago/RSocrata?branch=master (moved to https://coveralls.io/github/Chicago/RSocrata)
    From: README.md
    Status: 200
    Message: OK
```

https://win-builder.r-project.org/incoming_pretest/RSocrata_1.7.11-1_20210911_035815/Debian/00check.log
https://win-builder.r-project.org/incoming_pretest/RSocrata_1.7.11-1_20210911_035815/Windows/00check.log

**Comment by geneorama** [comment]
@nicklucius Starting this as a separate issue because it's truly unique.

I'm assuming that you want to call this `Version: 1.7.11-2`.  Let me know if you'd prefer `1.7.12-0`, `1.7.12-1` or something else.

**Comment by nicklucius** [comment]
@geneorama thanks, yep it will be 1.7.11-2.

**Comment by geneorama** [comment]
FYI, the URL for coveralls is not an HTTP/HTTPS issue.  

It looks like this is the original and replacement link pattern:
  https://coveralls.io/r/Chicago/RSocrata?branch=dev
  https://coveralls.io/github/Chicago/RSocrata?branch=dev

Also, some HTTP links were not in the check, but thought this would be a good time to update them as well.  I did the unnecessary HTTP changes in a separate commit so that they could be rolled back if there was a problem. 

Although I hesitate to make unnecessary changes, I felt that only updating the minimum necessary would fall more in the category of malicious compliance rather than scope creep.

**Comment by geneorama** [comment]
@nicklucius 

When I built I saw this message: 
```
==> devtools::check(args = c('--as-cran'))

-- Building ------ RSocrata --
Setting env vars:
------------------------------
i Installed roxygen2 version (7.1.1) doesn't match required version (6.1.1)
x check() will not re-document this package
------------------------------
* CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
* CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
* CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
------------------------------
```

The `DESCRIPTION` has this: "roxygen2 (>= 4.1.0)".

@nicklucius do you know why it's not rebuilding the help? I'm concerned that the old HTTP links will remain in the documentation.

**Comment by nicklucius** [comment]
This passed CRAN checks and is now live on CRAN.
