### ISSUE TITLE
Remove README from build

### ISSUE THREAD

**Issue by geneorama** [Chicago/RSocrata#226]
Unless there is some reason that we need to include it, it would be safer to exclude the readme from the build process because it includes links to sites that may be down, such as Socrata. 

@tomschenkjr @nicklucius Do either of you know of any problems with excluding the README from the build?

**Comment by nicklucius** [comment]
I don't think there are any problems it would cause, as far as I know.

**Comment by tomschenkjr** [comment]
I agree, there won't be any issues trying to install the package.

**Comment by geneorama** [comment]
Thanks for the speedy response!

I also finally set up my Github notifications from /Chicago to go to my work address so that I actually see your notifications immediately now. 

I hadn't done it in the past because I didn't want to get personal project notifications sent to work, which could have caused a conflict. Now you can route notifications by organization, which is quite handy!  I have no idea when that was implemented. 

I apologize for the meta conversation, but soon enough I'll bet in the next year Github will have an AI generated issue summary like Gitlab's and the clutter won't matter.
