### ISSUE TITLE
Update README.md to reflect reinstatement on CRAN

### ISSUE THREAD

**Issue by geneorama** [Chicago/RSocrata#228]

**Comment by ajlyons** [comment]
Thank you for getting RSocrata back on CRAN! 

Another little update you might want to make to README.md is that `install_github` is now part of the `remotes` package. It was split off from `devtools` a few years back (although `devtools` republishes it so legacy code still works).

**Comment by geneorama** [comment]
Thanks, that's good to know. Is there any advantage to changing? 

I'm inclined to keep `devtools` since that package is already used for checking and documenting, and it's not warning to switch. Thoughts? 

I was currently trying to figure out why the Travis and CRAN badges are not working as expected. Perhaps it's because the README.md was excluded from the package (for the CRAN badge).

**Comment by geneorama** [comment]
For now it's the same in the interests of getting the README updated.

**Comment by ajlyons** [comment]
I'm not sure about all the pros and cons of recommending users install the package with `remotes::install_github()` vs `devtools::install_github()`. devtools is of course a much bigger package and may be more of lift for users to install and have more impact on memory. The authors of devtools split off all the install_xxxx functions into [remotes](https://remotes.r-lib.org/) as a lightweight package that *only* installs packages from GitHub, GitLab, Bitbucket, Bioconductor. But whichever one you show in the README.md should have no bearing on the badges, checking and other continuous integration tasks.
