### ISSUE TITLE
Failure in posixify when no data

### ISSUE THREAD

**Issue by kent37** [Chicago/RSocrata#24]
If a query with a date column returns no data, posixify() fails with
```
Error in if (any(regexpr("^[[:digit:]]{1,2}/[[:digit:]]{1,2}/[[:digit:]]{4}$",  : 
  missing value where TRUE/FALSE needed
```

For example 
`read.socrata('https://data.cityofboston.gov/resource/awu8-dc52.csv?property_id=177808')`

**Comment by tomschenkjr** [comment]
Thank you. Also realizing that we never had a unit test that covered that issue. We'll look at #25 and integrate into our builds. I suspect our next stable CRAN submission will be in March.
