### ISSUE TITLE
JSON download error

### ISSUE THREAD

**Issue by geneorama** [Chicago/RSocrata#33]
Still working on reproducing this... but there's a JSON download error that happens in many with the Chicago data portal.

**Comment by tomschenkjr** [comment]
Is this the same download error as #19?

**Comment by geneorama** [comment]
Yes, I think the two issues are the same.  Actually, I think we should call this one the duplicate, and make #19 the original.

**Comment by tomschenkjr** [comment]
Since it's marked as duplicate, I'm closing it and moving the discussion to #19
