### ISSUE TITLE
Error executing read.socrata() for SODA UNDP data

### ISSUE THREAD

**Issue by nikiluk** [Chicago/RSocrata#34]
Error appears while executing *read.socrata()* for certain URL 

- But direct GET request to https://data.undp.org/resource/5tuc-d2a9.csv returns CSV without errors
read.socrata(requestquery_env) passes without any problem
- Get response test: 
https://www.hurl.it/?method=GET&url=https%3A%2F%2Fdata.undp.org%2Fresource%2F5tuc-d2a9.csv
- Screenshot: http://take.ms/gztzL

R code:

```
token="WFXsMsaWBDQN9niYCAgRtXRQj"

dataurl_env = "https://data.undp.org/resource/sf29-qtcx.csv"
dataurl_ind = "https://data.undp.org/resource/5tuc-d2a9.csv"
requestquery_env=paste(dataurl_env,"?$$app_token=",token, sep="")
requestquery_ind=paste(dataurl_ind,"?$$app_token=",token, sep="")

HDI_environment <- read.socrata(requestquery_env)
HDI_indicators <- read.socrata(requestquery_ind)
```

**Comment by dmpe** [comment]
ref: #35

**Comment by tomschenkjr** [comment]
These URLs, unfortunately, are no longer available so we can't reproduce this error. But since it's also related to #35, we'll use that issue to, perhaps, fix this one.
