### ISSUE TITLE
match.names error?

### ISSUE THREAD

**Issue by aburlock** [Chicago/RSocrata#35]
Noob here. Having some trouble with RSocrata and not sure where else to turn.

I'm trying to load data from Medicare's Home Health Compare. 
When I run "test<-read.socrata("https://data.medicare.gov/resource/6jpm-sxkc.json")"
I get: 
Error in match.names(clabs, names(xi)) : 
  names do not match previous names

Why is this happening?

**Comment by dmpe** [comment]
Hi @aburlock, 
we are avare of this, but for the moment you must use 
test<-read.socrata("https://data.medicare.gov/resource/6jpm-sxkc.csv")

Sorry for very late reply.

**Comment by geneorama** [comment]
This has long been resolved.
