### ISSUE TITLE
Implement code coverage suite intergration

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/RSocrata#41]
Integrate a code coverage suite (e.g., [coveralls.io](http://coveralls.io), [codecov](http://codecov.io)) with the RUnit testing.

Initial prototyping will be using the [covr](https://github.com/jimhester/covr) package to use code coverage implementation with Travis CI and Coveralls.

**Comment by tomschenkjr** [comment]
As part of this work, have broken-out  ```/R/tests``` into ```/tests``` so tests are executed during the ```R CMD build``` process, eliminating the need to include that step in the ```Makefile```.

**Comment by tomschenkjr** [comment]
Since ```tests``` directory is in root, need to remove the unit testing script from the CI yaml files.

**Comment by dmpe** [comment]
#48

**Comment by tomschenkjr** [comment]
Closed in cdda8f742014e669a93fecc8f362c3ce2cbb599c
