### ISSUE TITLE
"NA" in Dates Column

### ISSUE THREAD

**Issue by RPavuluri** [Chicago/RSocrata#68]
I ran the following in RScript:

health_FOIA <- read.socrata("https://data.cityofchicago.org/resource/4h87-zdcp.csv").

I then printed health_FOIA$DATE.RECEIVED and got NA for each entry. This is odd because there are dates in the online portal. It is also odd because I don't get NULL, which happens when I print health_FOIA$DATE.RECEIVEDS (incorrect spelling of column heading). 

When I print health_FOIA$DESCRIPTION.OF.REQUEST, however, I get a vector populated with the correct information. 

I have the same problem with the Business Affairs and Consumer Protection, Chicago Police Board, Fire, Ethics, Law, Human Resources, and Aviation FOIA Logs. 

Any thoughts?

**Comment by geneorama** [comment]
I'm having the same issue with the Sanitation data set
```R
sanitationComplaints <- read.socrata("https://data.cityofchicago.org/resource/me59-5fac.csv")
table(is.na(sanitationComplaints$Creation.Date))
# TRUE 
# 95360 
```
![image](https://cloud.githubusercontent.com/assets/1392068/13118584/8b412cda-d56a-11e5-9090-1369d553b382.png)
