### ISSUE TITLE
@context and @id missing from ls.socrata() download

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/RSocrata#72]
The `ls.socrata` function does not seem to download the `@context` and `@id` fields in `data.json` file. Need to investigate why this is happening.

``` json
{
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@id": "https://soda.demo.socrata.com/data.json",
  "@type": "dcat:Catalog",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "dataset": [
```

**Comment by chrismetcalf** [comment]
@tomschenkjr It looks like those feeds are present in [your `data.json` feed](http://data.cityofchicago.org/data.json), and at least visually they match with the [POD Data.JSON spec](https://project-open-data.cio.gov/v1.1/schema/). Is it an issue getting them into the RSocrata data frame then? 

Our team is available to help if you need it, just let us know!

**Comment by tomschenkjr** [comment]
Yeah, it's an issue with the `ls.socrata` function, thanks though!

**Comment by chrismetcalf** [comment]
OK, @mention me if there's anything I can help with then, good luck!

**Comment by tomschenkjr** [comment]
Fix submitted to `issue72` branch. 

The `@id` field (now coded as `x.id`, `@context` (`x.context`), `@type` (`x.type`), `conformsTo`, and `describedBy` is used to describe the entire file. So, it appears as repeated rows with the same value.

[See the example](https://github.com/Chicago/RSocrata/files/561048/new-ls-socrata.xlsx)

The first 5 columns basically inform the user that the metadata conforms to `v1.1` of the [Project Open Data](https://project-open-data.cio.gov/) schema. In the future, it's possible that newer metadata standards exist.

I am not a big fan of this since it's pretty repetitive. Perhaps we provide an optional argument in `ls.socrata()` which returns the metadata on the file. For instance, `ls.socrata(url = ..., schema=T)` which would return the first 5 columns, but only with one row.

**Comment by tomschenkjr** [comment]
After discussion with @geneorama and @nicklucius, going to use [data frame attributes](http://adv-r.had.co.nz/Data-structures.html#attributes) to define the `@id`, `@context`, `conformsTo`, and `describedBy`, or any other [catalog fields](https://project-open-data.cio.gov/v1.1/schema/).
