### ISSUE TITLE
RSocrata write.socrata function

### ISSUE THREAD

**Issue by joshmwolff** [Chicago/RSocrata#74]
Hello. First off, thank you for creating the RSocrata package. It is insanely useful and works beautifully. 

Second, any idea when the the write.socrata() function will go live? 

Thanks!

**Comment by tomschenkjr** [comment]
Thanks, Josh.


The function was submitted to CRAN last night, so hopefully in the next 36 hours.


Tom Schenk Jr.

Chief Data Officer

Department of Innovation and Technology

City of Chicago

(312) 744-2770

tom.schenk@cityofchicago.org

data.cityofchicago.org


________________________________

**Comment by tomschenkjr** [comment]
Received an update on this. There is a change with the most recent version of `httr` that was just introduced, which has [broken](https://travis-ci.org/Chicago/RSocrata/builds/105699970) our current development version. We're working on the fix.

We'll be discussing this fix more in our [Gitter](https://gitter.im/Chicago/RSocrata) channel.
