### ISSUE TITLE
Warning about invalid factor levels generated when downloading demo data (used in test)

### ISSUE THREAD

**Issue by geneorama** [Chicago/RSocrata#82]
In `RSocrata_1.7.0-14` a warning is generated when downloading the earthquake data:
![image](https://cloud.githubusercontent.com/assets/1392068/13295192/48c07dc4-daed-11e5-9cdb-61bf7242a209.png)

This warning didn't occur in previous versions, this example without the warning is based on the code in commit 1b92240f878b983ec01d7a7279aa09765aad52bf
![image](https://cloud.githubusercontent.com/assets/1392068/13295118/e937c9c0-daec-11e5-9a85-c072c56298ad.png)

**Comment by geneorama** [comment]
I narrowed it down to 8446c896a5b88b09dac7d55418063e29eed652b1.

This is also when RSocrata started defaulting to factors instead of character for text columns.

**Comment by geneorama** [comment]
I don't get this warning in #86

**Comment by tomschenkjr** [comment]
Can this also be closed now?

**Comment by geneorama** [comment]
Yes, thanks for reminding me.
