### ISSUE TITLE
Check for potential issues with upcoming httr 1.1.0.9000 release

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/RSocrata#95]
Received a notification on upcoming changes to `httr` and appears there may be an RSocrata error that came up.

(My guess is the error is simply colliding uploading between the AppVeyor and Travis CI. Let's just rerun locally and see if we can replicate the error)

```
I found: 1 error  | 0 warnings | 0 notes.

    checking tests ... ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      [2]  261 - -344 ==  605
      [3]  891 -   65 ==  826
      [4] -108 -  680 == -788
      [5] -416 -   16 == -432


      testthat results
================================================================
      OK: 96 SKIPPED: 0 FAILED: 2
      1. Failure: fully replace a dataset (@test-all.R#275)
      2. Failure: fully replace a dataset (@test-all.R#276)

      Error: testthat unit tests failed
      Execution halted

If I got an ERROR because I couldn't install your package (or one of it's dependencies), my apologies. You'll have to run the checks yourself (unfortunately I don't have the time to diagnose installation failures as I have to run checks on hundreds of packages).

Otherwise, please carefully look at the results, and let me know if I've introduced a bug in httr. If I have, I'd really appreciate a minimal reproducible example that uses only httr functions. That way I can find and fix the bug as quickly as possible.

If it doesn't look like a bug in httr, please prepare an update for CRAN. Ideally you'll tweak your package so it works with both the released and development versions of dplyr. Otherwise, be prepared to submit your package to CRAN soon after I let you know that I've submitted.

To get the development version of httr so you can run the checks yourself, you can run:

    # install.packages("devtools")
    devtools::install_github("hadley/httr")

To see what's changed visit
<https://github.com/hadley/httr/blob/master/NEWS.md>.
```

**Comment by geneorama** [comment]
My latest R CMD check result "exited with Status 15".  I don't know where to find documentation on this status, but I suspect it's a time out error. 

The test script hangs on the final test "fully replace a dataset", specifically, it hangs on this line: `write.socrata(df_in,datasetToReplaceUrl,"REPLACE",socrataEmail,socrataPassword)`.  I deleted the entire script except for that part of the test, and the test hangs.  

Notes:

- The "add a row to a dataset" test succeeds. 
- There is no problem when manually stepping through the tests, the problem only happens when running `R CMD check`.
- My results were not consistent, I also encountered an CURL memory error on one iteration in the "Read data with missing dates" test 

I am running the tests with the `--as-cran` option

Also, my `sessionInfo()`
```R
R version 3.2.5 (2016-04-14)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.1.0.9000 R6_2.1.2        tools_3.2.5     withr_1.0.1     curl_0.9.7      memoise_1.0.0   knitr_1.12.3   
 [8] git2r_0.14.0    digest_0.6.9    devtools_1.11.1
```

**Comment by geneorama** [comment]
Just now while testing I found that the `httr::PUT` command hangs.  It seemed to be working yesterday when I manually ran the tests, but when I run the command while stepping through the function using `browser()`, it fails. 

It seems that `PUT` doesn't work when building or when using browser, which suggests to me that it's a problem with inter-environment communication with `PUT`.  I've used Hadley's `pryr` package for my own analysis of such issues.

Line where hang happens: https://github.com/Chicago/RSocrata/blob/master/R/RSocrata.R#L333
/play 56k

**Comment by tomschenkjr** [comment]
So, `R CMD check` fails but manually running each unit test works?

**Comment by geneorama** [comment]
@tomschenkjr 
- The final test fails if you run `R CMD check` (in either R Studio, or at the command line)
- The final test works if you run it manually
- Each command within the final test works
- However, if you insert a call to `browser()` in `checkUpdateResponse ()` and step through the code final test, then the call to `http::PUT` hangs / times out, which is the same thing that happens when you run `R CMD check`

**Comment by tomschenkjr** [comment]
Could it be that the writes to Socrata are conflicting with each other? That is, the write isn’t done before it goes to the next test?

**Comment by geneorama** [comment]
@tomschenkjr Sorry, I thought I already replied to this. I don't think it's Socrata calls in conflict.

I did just find an interesting clue:

The following code will work in the R GUI, but it hangs in R Studio (I tried it in R Studio first, so it's not likely that it's a Socrata conflict):
```R
email <- "mark.silverberg+soda.demo@socrata.com"
pw <- "7vFDsGFDUG"
url <- "https://soda.demo.socrata.com/resource/kc76-ybeq.json"

df <- jsonlite::toJSON(data.frame(x = sample(-1000:1000, 5), 
                                  y = sample(-1000:1000, 5)))
browser()
resp <- httr::PUT(url,
                  body = df,
                  httr::authenticate(email, pw),
                  httr::add_headers("X-App-Token" = NULL,
                                    "Content-Type" = "application/json"))
```

**Comment by geneorama** [comment]
The code in the test script uses `Sys.getenv`, e.g.: `socrataEmail <- Sys.getenv("SOCRATA_EMAIL", "mark.silverberg+soda.demo@socrata.com")`.

This doesn't seem to be causing the hang, but I can imagine it being a potential source of error during the build process.

**Comment by tomschenkjr** [comment]
@geneorama - we can close this right? This turned out to be an issue with `httr` didn't it?

**Comment by geneorama** [comment]
Yes!  And it's been fixed. Closing now.
